version: '3'

networks:
  propellerads_net:
    driver: bridge

services:
  propellerads_nginx:
    image: nginx:stable
    container_name: propellerads_nginx
    restart: unless-stopped
    ports:
      - 7777:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - propellerads_php
    networks:
      - propellerads_net
  
  propellerads_php:
    build:
      context: ./
      dockerfile: ./docker/php/php.Dockerfile
    container_name: propellerads_php
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/supervisord:/etc/supervisor/conf.d
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
      - ./docker/php/my_custom_conf.ini:/usr/local/etc/php/conf.d/my_custom_conf.ini
      - ./docker/php/php-fpm/zz-docker-override.conf:/usr/local/etc/php-fpm.d/zz-docker-override.conf
    networks:
      - propellerads_net
    command: sh -c "/usr/bin/supervisord"
  
  propellerads_redis:
    container_name: propellerads_redis
    restart: always
    image: "redis"
    volumes:
      - ./docker/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - propellerads_net
